- name: install kubelet and kubectl
  yum:
    name: "{{ item }}"
    state: lates
  with_items:
    - kubelet
    - kubectl

- name: enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: create kubernetes cluster and apply network driver (calico)
  shell: |
    kubeadm init --pod-network-cidr=192.168.0.0/16;
    mkdir -p $HOME/.kube;
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config;
    sudo chown $(id -u):$(id -g) $HOME/.kube/config;
    kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml
